# AI Helper Configuration File
# This file contains configuration settings for the AI Helper plugin features

# Auto-completion settings for inline text completion
autocompletion:
  # Debounce delay in milliseconds - wait time after user stops typing before triggering completion
  debounce_delay: 500
  
  # Minimum character count required to trigger auto-completion
  min_length: 5
  
  # Maximum number of sentences in completion response (1-3)
  max_sentences: 3
  
  # Color of the inline completion suggestion text (CSS color value)
  suggestion_color: "#888888"
  
  # Enable/disable auto-completion feature globally (can be overridden per user)
  enabled_by_default: true
  
  # Wiki-specific auto-completion settings
  wiki_min_length: 10
  wiki_max_sentences: 5

# Model Context Protocol (MCP) server configurations
# This section is for existing MCP functionality and should not be modified
mcp_servers: []

# Langfuse integration settings for observability
# This section is for existing Langfuse functionality
langfuse:
  enabled: false